### ISSUE TITLE
板载AX200 wifi问题

### ISSUE THREAD

**Issue by 3Alan** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#1]
请问wifi会不会经常断，我的wifi有时特别不稳定

**Comment by QQ3233** [comment]
不会断流啊，正常使用，你是用我的EFI文件吗

**Comment by 3Alan** [comment]
我之前用的是其他人的，蓝牙和wifi都不稳定。等我试试你的看看，感谢！

**Comment by QQ3233** [comment]
你可以先试一下我都引导文件，跟我的配置一样的硬件不会出现断流的情况

**Comment by uax** [comment]
蓝牙可以使用吗？我用了你的 wifi 正常，但是蓝牙识别不到任何设备。

**Comment by QQ3233** [comment]
> 蓝牙可以使用吗？我用了你的 wifi 正常，但是蓝牙识别不到任何设备。

主板是一样的吗

**Comment by uax** [comment]
> > 蓝牙可以使用吗？我用了你的 wifi 正常，但是蓝牙识别不到任何设备。
> 
> 主板是一样的吗

一样的，蓝牙没问题了。但是无法使用隔空投送、接力等。
后来买了 奋威的 T91。

**Comment by supercoding** [comment]
我刚换了0.7.2的EFI，蓝牙可以识别，wifi显示“电缆已拔出”，难道我的WIFI模块坏了？

**Comment by sunO2** [comment]
> > > 蓝牙可以使用吗？我用了你的 wifi 正常，但是蓝牙识别不到任何设备。
> > 
> > 
> > 主板是一样的吗
> 
> 一样的，蓝牙没问题了。但是无法使用隔空投送、接力等。
> 后来买了 奋威的 T91。

你好 蓝牙是怎么处理的呢
我用的也是这个 EFI 
主板B460M 迫击炮WIFI
我也是蓝牙不可用

**Comment by QQ3233** [comment]
> 
> 
> > > > 蓝牙可以使用吗？我用了你的 wifi 正常，但是蓝牙识别不到任何设备。
> > > 
> > > 
> > > 主板是一样的吗
> > 
> > 
> > 一样的，蓝牙没问题了。但是无法使用隔空投送、接力等。
> > 后来买了 奋威的 T91。
> 
> 你好 蓝牙是怎么处理的呢 我用的也是这个 EFI 主板B460M 迫击炮WIFI 我也是蓝牙不可用

你更新最新版的EFI文件试一下
