### ISSUE TITLE
i7-10700应该也是直接可以使用的吧？

### ISSUE THREAD

**Issue by frankfoofoo** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#2]

**Comment by QQ3233** [comment]
可以，主板一致就可以了

**Comment by dpawsbear** [comment]
我的10400也上车了。

**Comment by Oosl** [comment]
> 可以，主板一致就可以了

好耶，10700F+RX550成功上车。一开始一直卡在PCI confguration begin。弄了很久都不行，最后尝试发现时BIOS问题，BIOS重置后完全按照你README的改就成功了！谢谢！🙏
