### ISSUE TITLE
睡眠之后唤醒，显示器无信号，需要重启显示器才行

### ISSUE THREAD

**Issue by coder30** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#6]
有人和我遇到一样的问题吗？求解答

**Comment by QQ3233** [comment]
没有发现这个问题，建议你看看显示器是不是开启了什么节能模式

**Comment by freprite** [comment]
我的是双显示器也有这个问题，一个4K显示器用DP口，一个1080P显示器用HDMI口。锁屏后唤醒只能唤醒1080P的显示器。4K的显示器需要关闭再开启。

**Comment by fxinren** [comment]
显示器无法唤醒很可能跟黑苹果无关，白果从17款macbookpro开始，系统版本当时都是10.13,10,14，链接dell显示器，就无法唤醒，我的现象是需要重新拔插hdmi线，显示器可以唤醒，我们同事和我的现象不一样，他需要开关显示器，才能唤醒。我们德mbp都是公司配的同型号，dell显示器也是同型号，hdmi线也是公司的，但是批次不同，厂家不同。顺便说下，相同的dell显示器，相同的hdmi线，2015款mbp从来没有出现过这个问题。系统版本也是10,13，10.14。这个信息供各位参考
