### ISSUE TITLE
USB定制修正

### ISSUE THREAD

**Issue by Oosl** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#7]
如题，这两天白嫖Repo的EFI成功装机成功，使用了半天后发现USB虽然定制过，且都能使用，但是存在一个问题，几乎所有接口都是只能使用USB2.0接口，于是找教程研究了一下，更正了在我这里正常使用的USB接口定制。

下图是我试出的所有的接口的定义图。图中右下角为在Hackintool中定制USB的截图，有动手能力的参照此定制后导出，[也可尝试我定制完的kext](https://wwe.lanzoui.com/iuawasdpnpe) 密码:gvws。
![B460USB](https://user-images.githubusercontent.com/27420243/128631693-4deefd8b-b5f5-419d-bd8c-4b0785ac328d.png)

最后得到的文件是USBPorts.kext，丢到EFI中启用，同时禁用原来的USBMap.kext（和USBInjectAll.kext)。重启即可～

PS：建议在README中添加一个提示，要是安装时遇到奇奇怪怪的问题，强烈建议重置BIOS/严格按照你的BIOS设置。

最后十分感谢你的作业～

**Comment by frankfoofoo** [comment]
> 如题，这两天白嫖Repo的EFI成功装机成功，使用了半天后发现USB虽然定制过，且都能使用，但是存在一个问题，几乎所有接口都是只能使用USB2.0接口，于是找教程研究了一下，更正了在我这里正常使用的USB接口定制。
> 
> 下图是我试出的所有的接口的定义图。图中右下角为在Hackintool中定制USB的截图，有动手能力的参照此定制后导出，[也可尝试我定制完的kext](https://wwe.lanzoui.com/iuawasdpnpe) 密码:gvws。
> ![B460USB](https://user-images.githubusercontent.com/27420243/128631693-4deefd8b-b5f5-419d-bd8c-4b0785ac328d.png)
> 
> 最后得到的文件是USBPorts.kext，丢到EFI中启用，同时禁用原来的USBMap.kext（和USBInjectAll.kext)。重启即可～
> 
> PS：建议在README中添加一个提示，要是安装时遇到奇奇怪怪的问题，强烈建议重置BIOS/严格按照你的BIOS设置。
> 
> 最后十分感谢你的作业～

最后得到的文件是USBPorts.kext，丢到EFI中启用，同时禁用原来的USBMap.kext（和USBInjectAll.kext)。重启即可～

小白提问，请问这个怎么操作?^ _ ^

**Comment by Oosl** [comment]
> 最后得到的文件是USBPorts.kext，丢到EFI中启用，同时禁用原来的USBMap.kext（和USBInjectAll.kext)。重启即可～
> 
> 小白提问，请问这个怎么操作?^ _ ^ 

建议B站和网上找一下教程如何配置OC类似的教程，基本懂一些基础的操作。这里步骤应该已经描述得很清楚。如果是不知道怎么禁用的话，是通过编辑config.plist禁用/启用的，编辑的工具有很多，此Repo README中好像也有写。

**Comment by Oosl** [comment]
@QQ3233 我从头制作了一份OC0.7.2的版本，放到了[我的仓库](https://github.com/Oosl/MSI-B460WIFI-10700F-RX550-4G)，README介绍使用你的README修改而成（已著名来源），如有冒犯，请告诉我，我会及时修改。

**Comment by QQ3233** [comment]
很高兴能帮到你，我的文件你可以拿来根据你的主机实际情况自行修改，我的文件在定制USB的时候考虑到我的前面板端口的因素，全部使用了USB2.0，同时也非常感谢你的建议，晚点得空更新版本的时候我再修订一下。

**Comment by beta4better** [comment]
请问下板载的两个USB接口的名称是什么啊？那个JUSB1和JUSB2.

**Comment by Oosl** [comment]
> 请问下板载的两个USB接口的名称是什么啊？那个JUSB1和JUSB2.

那个我没用，你要自己试
