### ISSUE TITLE
readme的第五项 应该是 内核设置 吧，目前是内接设置

### ISSUE THREAD

**Issue by hansky1211** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#8]
readme的第五项 应该是 内核设置 吧，目前是内接设置。。
--------------------------------------------------
efi用上了，很舒服 10400 b460m迫击炮wifi  科赋8g*2  inter 535 240g

**Comment by QQ3233** [comment]
很高兴能帮上忙
