### ISSUE TITLE
网络唤醒问题

### ISSUE THREAD

**Issue by sunO2** [QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630#9]
你好 麻烦问下 你那边网络唤醒能用不 WOL 网络唤醒
并且麻烦帮忙看下 设置---> 节能 
你那边显示的是 
    1.唤醒以供网络访问
    2.唤醒以供WIFI 访问
这两个中的哪个呢
     谢谢

**Comment by QQ3233** [comment]
没有使用过硬件唤醒，目前使用的todesk没发现什么问题
